baseURL = ""
languageCode = "en-us"
title = "scOrange"
paginate = 4 #frontpage pagination
disqusShortname = "localblog-2"

[outputFormats]
  [outputFormats.workflow]
    mediaType = "application/json"
    baseName = "workflow"
    notAlternative = true
  [outputFormats.blog]
    mediaType = "application/json"
    baseName = "blog"
    notAlternative = true

[outputs]
  home = [ "HTML", "workflow", "blog"]

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/#features"
    weight = -130

  [[menu.main]]
    name = "Screenshots"
    url = "/screenshots/"
    weight = -120

  [[menu.main]]
    name = "Workflows"
    url = "/workflows/"
    weight = -110

  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = -100

  [[menu.main]]
    identifier = "download"
    name = "Download"
    url = "/download/"
    weight = -90

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = -80

  



